version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/backend
    overwrite: yes
permissions:
  - object: /home/ec2-user/app/backend/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
environment:
  variables:
    AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    AWS_REGION: "ap-northeast-2"
    AWS_STACK_AUTO: "false"
    JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
    JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
