version: 0.0
os: linux

# 파일 복사 설정 - 기존 파일 덮어쓰기 동작 명시
files:
  - source: /
    destination: /home/ec2-user/app/backend
    overwrite: yes
    file_exists_behavior: OVERWRITE  # 파일이 이미 존재할 경우 덮어쓰기

# 파일 권한 설정
permissions:
  - object: /home/ec2-user/app/backend/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

# 환경 변수 설정 (AWS SDK 표준 형식)
environment:
  variables:
    # AWS 자격증명 설정
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    AWS_REGION: "ap-northeast-2"
    AWS_STACK_AUTO: "false"

    # JWT 설정
    JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
    JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}

# 배포 수명주기 훅 설정
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user

