name: Backend CI/CD  # CI/CD 파이프라인 이름

# GitHub Actions 트리거 설정
on:
  push:
    branches: [main, dev]  # main과 dev 브랜치에 push 발생 시
    paths:
      - '**'  # 모든 경로의 파일 변경 감지
  pull_request:
    branches: [main, dev]  # main과 dev 브랜치로의 PR
    types: [opened, reopened, closed, synchronize]  # PR 이벤트 타입 지정
    paths:
      - '**'  # 모든 경로의 파일 변경 감지

jobs:
  build:  # 빌드 작업 정의
    runs-on: ubuntu-latest  # Ubuntu 최신 버전에서 실행
    environment: development  # development 환경 사용 (시크릿 접근용)
    defaults:
      run:
        working-directory: .  # 작업 디렉토리 설정

    steps:
      - uses: actions/checkout@v3  # 소스 코드 체크아웃

      # Parameter Store에 시크릿 저장
      - name: Store secrets in Parameter Store
        run: |
          aws ssm put-parameter --name /development/AWS_ACCESS_KEY_ID --value ${{ secrets.AWS_ACCESS_KEY_ID }} --type SecureString --overwrite
          aws ssm put-parameter --name /development/AWS_SECRET_ACCESS_KEY --value ${{ secrets.AWS_SECRET_ACCESS_KEY }} --type SecureString --overwrite
          aws ssm put-parameter --name /development/AWS_S3_BUCKET --value ${{ secrets.AWS_S3_BUCKET }} --type SecureString --overwrite
          aws ssm put-parameter --name /development/JWT_SECRET_KEY --value ${{ secrets.JWT_SECRET_KEY }} --type SecureString --overwrite
          aws ssm put-parameter --name /development/JWT_EXPIRATION --value ${{ secrets.JWT_EXPIRATION }} --type SecureString --overwrite
          aws ssm put-parameter --name /development/JWT_REFRESH_EXPIRATION --value ${{ secrets.JWT_REFRESH_EXPIRATION }} --type SecureString --overwrite

      - name: Validate Gradle wrapper  # Gradle Wrapper 유효성 검사
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17  # JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'  # Zulu OpenJDK 사용
          cache: 'gradle'  # Gradle 캐싱으로 빌드 속도 향상

      - name: Grant execute permission for gradlew  # gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Run tests  # 테스트 실행
        env:
          SPRING_PROFILES_ACTIVE: test  # 테스트 프로필 활성화
        run: ./gradlew test --stacktrace

      - name: Build with Gradle  # Gradle 빌드 실행
        if: success()  # 이전 단계 성공 시에만 실행
        run: ./gradlew build -x test  # 테스트 제외하고 빌드

      - name: Upload JAR  # JAR 파일을 아티팩트로 저장
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: build/libs/*.jar

      - name: Upload test results  # 테스트 결과 업로드
        if: always()  # 항상 실행
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test

  deploy:  # 배포 작업 정의
    needs: build  # build 작업 완료 후 실행
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    environment: development  # development 환경의 시크릿 사용

    steps:
      - uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p build/libs

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: jar-file
          path: build/libs

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws deploy push \
            --application-name youtube-app \
            --s3-location s3://youtube-deploy/youtube-app.zip \
            --source .

      - name: Deploy to EC2
        run: |
          aws deploy create-deployment \
            --application-name youtube-app \
            --deployment-group-name youtube-group \
            --s3-location bucket=youtube-deploy,key=youtube-app.zip,bundleType=zip
