name: Backend CI/CD  # CI/CD 파이프라인의 이름

# main, dev 브랜치에 push 되거나 PR이 생성/수정될 때 실행되는 트리거 설정
on:
  push:
    branches: [main, dev]  # main과 dev 브랜치에 push될 때
    paths:
      - '**'  # 모든 경로의 파일 변경 감지
  pull_request:
    branches: [main, dev]  # main과 dev 브랜치로의 PR
    types: [opened, reopened, closed, synchronize]  # PR 이벤트 타입들
    paths:
      - '**'  # 모든 경로의 파일 변경 감지

jobs:
  build:  # 빌드 작업 정의
    runs-on: ubuntu-latest  # Ubuntu 최신 버전에서 실행
    defaults:
      run:
        working-directory: .  # 작업 디렉토리 설정

    steps:
      - uses: actions/checkout@v3  # 소스 코드 체크아웃

      - name: Validate Gradle wrapper  # Gradle Wrapper 검증
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17  # JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'  # Zulu OpenJDK 사용
          cache: 'gradle'  # Gradle 캐싱으로 빌드 속도 향상

      - name: Grant execute permission for gradlew  # gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Run tests  # 테스트 실행
        env:
          # AWS 관련 설정
          AWS_ACCESS_KEY: ${{ secrets.TEST_AWS_ACCESS_KEY }}  # 테스트용 AWS 접근 키
          AWS_SECRET_KEY: ${{ secrets.TEST_AWS_SECRET_KEY }}  # 테스트용 AWS 시크릿 키
          AWS_REGION: ap-northeast-2  # AWS 서울 리전
          AWS_S3_BUCKET: test-bucket  # 테스트용 S3 버킷
          AWS_STACK_AUTO: false  # AWS 스택 자동 생성 비활성화

          # JWT 관련 설정
          JWT_SECRET_KEY: 7134743777217A25432A462D4A614E645267556B58703272357538782F413F4428472B4B6250655368566D597133743677397A244326452948404D635166546A  # JWT 시크릿 키
          JWT_EXPIRATION: 3600000  # JWT 만료 시간 (1시간)
          JWT_REFRESH_EXPIRATION: 86400000  # JWT 리프레시 토큰 만료 시간 (24시간)

          # Spring 프로필 설정
          SPRING_PROFILES_ACTIVE: test  # 테스트 프로필 활성화
        run: ./gradlew test --stacktrace  # 테스트 실행 (상세 로그 출력)

      - name: Build with Gradle  # Gradle로 프로젝트 빌드
        if: success()  # 테스트 성공 시에만 실행
        run: ./gradlew build -x test  # 테스트 제외하고 빌드

      - name: Upload test results  # 테스트 결과 업로드
        if: always()  # 항상 실행
        uses: actions/upload-artifact@v3
        with:
          name: test-results  # 결과물 이름
          path: build/reports/tests/test  # 테스트 결과 경로

  deploy:  # 배포 작업 정의
    needs: build  # build 작업 완료 후 실행
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)  # main 브랜치 push 또는 PR 병합 시에만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials  # AWS 인증 정보 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS 접근 키
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS 시크릿 키
          aws-region: ap-northeast-2  # AWS 서울 리전

      - name: Upload to S3  # S3에 빌드 파일 업로드
        run: |
          aws deploy push \
            --application-name youtube-app \
            --s3-location s3://youtube-deploy/youtube-app.zip \
            --source .

      - name: Deploy to EC2  # EC2에 배포
        run: |
          aws deploy create-deployment \
            --application-name youtube-app \
            --deployment-group-name youtube-group \
            --s3-location bucket=youtube-deploy,key=youtube-app.zip,bundleType=zip
